acervo/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acervo_pessoal/', include('acervo_pessoal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acervo_pessoal/urls.py
from django.urls import path
from .views.gerenciarEmprestimo import *
from .views.gerenciarContato import *
from .views.gerenciarLivro import *
from .views.home import *
from .views.outros import *
from django.contrib.auth.views import *

app_name = 'acervo_pessoal'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('home_logado/', HomePageLogadoView.as_view(), name='home_logado'), 
    path('cadastro/', CadastroView.as_view(), name='cadastro'),
    path('login/', LoginView.as_view(), name='login'),
    path('meu_perfil/', MeuPerfilView.as_view(), name='perfil'), 
    path('logout/', LogoutView.as_view(), name='logout'),
    path('cadastrar_livro/', CadastrarLivroView.as_view(), name='cadastrar_livro'),
    path('cadastrar_contato/', CadastrarContatoView.as_view(), name='cadastrar_contato'),
    path('registrar_emprestimo/', RegistrarEmprestimoView.as_view(), name='registrar_emprestimo'),
    path('registrar_devolucao/', RegistrarDevolucaoView.as_view(), name='registrar_devolucao'),
    path('listar_itens/', ListarItensView.as_view(), name='listar_itens'),
    path('pesquisar_livros/', PesquisarLivroView.as_view(), name='pesquisar_livros'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acervo_pessoal/', include('acervo_pessoal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

acervo_pessoal/models/contato.py
from django.db import models
from django.contrib.auth.models import User

class Contato(models.Model):
    nome =  models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, related_name='contatos', null=True, blank=True)
    
    def __str__(self):
        return "Nome: " + self.nome + " Email: " + self.email
    

acervo_pessoal/models/emprestimo.py
from django.db import models 
from acervo_pessoal.models.livro import Livro
from acervo_pessoal.models.contato import Contato
from django.contrib.auth.models import User
from django.utils import timezone

class Emprestimo(models.Model):
    livro = models.ForeignKey(Livro, on_delete=models.CASCADE)
    contato = models.ForeignKey(Contato, on_delete=models.CASCADE)
    data_emprestimo = models.DateTimeField(default=timezone.now)
    data_devolucao = models.DateTimeField(blank=True, null=True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    status_emprestimo = models.CharField(max_length=10, choices= [ ('ativo', 'Ativo'),
        ('devolvido', 'Devolvido')], default='ativo')
    
    def __str__(self):
        return "Livro "+ str(self.livro) + " emprestado para "+ str(self.contato) + " em " + str(self.data_emprestimo) + " status: "+ str(self.status_emprestimo)
    
""" def registrar_devolucao(self):
        self.status_emprestimo = 'devolvido'
        self.data_devolucao = timezone.now()
        self.save() # salva mesmo no banco de dados
"""

acervo_pessoal/models/livro.py
from django.db import models
from django.contrib.auth.models import User

class Livro(models.Model):
    nome = models.CharField(max_length=255)
    autor = models.CharField(max_length=255)
    ano  = models.IntegerField()
    foto = models.ImageField(upload_to='capas/')
    usuario = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return "Nome: " + self.nome + " Autor: " + self.autor + " Ano: " + str(self.ano)

acervo_pessoal/views/gerenciarContato.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from ..models.contato import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

class CadastrarContatoView(View):
     def get(self, request, *args, **kwargs):
        contatos = Contato.objects.filter(usuario=request.user).order_by('-id')
        return render(request, 'cadastrar_contato.html', {'contatos': contatos})
    
     def post(self, request, *args, **kwargs):
         nome = request.POST.get('nome')
         email = request.POST.get('email')

         contato = Contato(nome=nome, email=email, usuario=request.user)
         contato.save()
         return redirect(request.META.get('HTTP_REFERER'))

acervo_pessoal/views/gerenciarEmprestimo.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views import View
from ..models.livro import *
from ..models.contato import *
from ..models.emprestimo import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

class RegistrarEmprestimoView(View):
    def get(self, request, *args, **kwargs):
        emprestimos = Emprestimo.objects.filter(usuario=request.user).order_by('-id')
        #livros = Livro.objects.filter(usuario=request.user)
        contatos = Contato.objects.filter(usuario=request.user)
        # mostrar livros disponiveis para empréstimo:
        ## pegar todos os ids dos livros que tem emprestimos ativos e retirar dos livros disponiveis
        livros_emprestados_identificadores = Emprestimo.objects.filter(usuario=request.user, status_emprestimo='ativo').values_list('livro_id', flat=True)
        ## fazer uma lista de livros disponiveis retirando os emprestados 
        livros_disponiveis = Livro.objects.filter(usuario=request.user).exclude(id__in=livros_emprestados_identificadores)

        return render(request, 'registrar_emprestimo.html', {'emprestimos': emprestimos, 'livros':livros_disponiveis, 'contatos':contatos})
    
    def post(self, request, *args, **kwargs):
        livro_id = request.POST.get('livro') #pega o id do livro
        contato_id = request.POST.get('contato') 

        #procura por id para poder enviar para a criação do emprestimo
        livro = get_object_or_404(Livro, id=livro_id)
        contato = get_object_or_404(Contato, id=contato_id)

        emprestimo = Emprestimo(
                livro= livro,
                contato= contato,
                data_devolucao= None,
                usuario=request.user,
                status_emprestimo='ativo'
        )
        emprestimo.save()
        return redirect(request.META.get('HTTP_REFERER'), )
    

class RegistrarDevolucaoView(View):
    def get(self, request, *args, **kwargs):
        emprestimos_ativos = Emprestimo.objects.filter(usuario=request.user, status_emprestimo='ativo').order_by('-data_emprestimo')
        livros_emprestados = Livro.objects.filter(emprestimo__usuario=request.user, emprestimo__status_emprestimo='ativo').distinct()
        return render(request, 'registrar_devolucao.html', {'emprestimos_ativos': emprestimos_ativos, 'livros_emprestados': livros_emprestados})

    def post(self, request, *args, **kwargs):
        livro_id = request.POST.get('livro')
        livro = get_object_or_404(Livro, id=livro_id, usuario=request.user) # acha o livro pelo id
        emprestimo = Emprestimo.objects.filter(livro=livro, usuario=request.user, status_emprestimo='ativo').first() # procura o empréstimo desse livro escolhido
        if (emprestimo): # se o emprestimo existir
             emprestimo.status_emprestimo = 'devolvido' # muda o status do emprestimo para devolvido
             emprestimo.data_devolucao = timezone.now() # envia valor de devolvido para o emprestimo
             emprestimo.save() # salva o emprestimo
        
        return redirect(request.META.get('HTTP_REFERER'))
    
class ListarItensView(View):
    def get(self, request, *args, **kwargs):
        ## pegar todos os ids dos livros que tem emprestimos ativos e retirar dos livros disponiveis
        livros_emprestados_identificadores = Emprestimo.objects.filter(usuario=request.user, status_emprestimo='ativo').values_list('livro_id', flat=True)
        ## fazer uma lista de livros disponiveis retirando os emprestados 
        livros_disponiveis = Livro.objects.filter(usuario=request.user).exclude(id__in=livros_emprestados_identificadores) # DISPONIVEIS

        ## pegar todos os ids dos livros que tem emprestimos e adicionar em livros emprestados
        livros_emprestados = Livro.objects.filter(id__in=livros_emprestados_identificadores)# EMPRESTADOS

        return render(request, 'listar_itens.html', {'livros_disponiveis': livros_disponiveis, 'livros_emprestados': livros_emprestados})

acervo_pessoal/views/gerenciarLivro.py
from django.shortcuts import render, redirect
# Create your views here.
from django.views import View
from ..models.livro import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect

class CadastrarLivroView(View):
    def get(self, request, *args, **kwargs):
        livros = Livro.objects.filter(usuario=request.user).order_by('-id')
        return render(request, 'cadastrar_livro.html', {'livros': livros})
    
    def post(self, request, *args, **kwargs):
         nome = request.POST.get('nome_livro')
         autor = request.POST.get('autor')
         ano = request.POST.get('ano')
         foto = request.FILES.get('foto_livro')

         livro = Livro(nome=nome, autor=autor, ano=ano, foto=foto, usuario=request.user)
         livro.save()
         return redirect(request.META.get('HTTP_REFERER'))
    
class PesquisarLivroView(View):
     def get(self, request, *args, **kwargs):
          pesquisa = request.GET.get('p', '') # se o usuário não digitar a variável 'p', ele vai só dar enter sem nada, por isso precisa de dois argumentos
          livros_do_acervo = Livro.objects.filter(usuario=request.user, nome__icontains=pesquisa)
          return render(request, 'livros_pesquisados.html', {'livros': livros_do_acervo})

acervo_pessoal/views/home.py
from django.shortcuts import render, redirect
from django.views import View
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User

class HomeView(View):
      def get(self, request, *args, **kwargs):
        return redirect('acervo_pessoal:home_logado') if request.user.is_authenticated else render(request, 'home.html')

class HomePageLogadoView(View):
      def get(self, request, *args, **kwargs):
        user = request.user
        return render(request, 'pag_inicial_logado.html', {'user': user})

acervo_pessoal/views/outros.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View
from ..models.emprestimo import *
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.hashers import make_password
from django.contrib.auth import authenticate, logout


class CadastroView(View):
     def get(self, request, *args, **kwargs):
        return render(request, 'cadastro.html')
    
     def post(self, request, *args, **kwargs):
         nome = request.POST.get('fname')
         username = request.POST.get('fusername')
         email = request.POST.get('email')
         senha = request.POST.get('password')
        
        # criar novo usuário:
         user = User.objects.create_user(
            username=username,
            email = email,
            first_name = nome,
            password = senha,
         )
         user.save()
         return redirect('acervo_pessoal:login')
         

class LoginView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')
    
    def post(self, request, *args, **kwargs):
        # verificação dos dados para validar o login
        username = request.POST.get('username')
        password = request.POST.get('password')

        # ver se o usuário existe no bd
        user = authenticate(request, username=username, password=password)

        #se o user receber 'none', n tem usuário, se receber outra coisa, as credenciais são inválidas

        if(user != None):
            login(request, user) 
            return redirect('acervo_pessoal:home_logado')  
        
        else:
            return render(request, 'login.html', {'error': 'Houve um erro no seu login, tente novamente. Talvez sua senha esteja errada'})

class MeuPerfilView(View):
    def get(self, request, *args, **kwargs):
        user = request.user
        return render(request, 'meu_perfil.html', {'user':user})

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('acervo_pessoal:home')

acervo_pessoal/templates/base_logado.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/base_logado.css'%}">
    <title>{% block titulo %}Homepage{% endblock %}</title>
</head>
<body>
    {% block navbar %}
    <nav>
        <ul class="nav-bg-logado">
            <li  class="logo li-nav-logado"><img src="{% static 'images/logo.svg' %}"></li>
            <li  class="logo-texto li-nav-logado"><a href="#home">Acervo Pessoal Samara</a></li>
            <li class="barra-pesquisa li-nav-logado">
                <form action="{% url 'acervo_pessoal:pesquisar_livros' %}" method="get" class="form-pesquisa">
                    <input type="text" name="p" placeholder="Pesquisar livros..." class="pesquisa-input">
                    <button type="submit" class="pesquisa-botao">Buscar</button>
                </form>
            </li>
            <li  class="img-profile li-nav-logado" style="float:right">
                <a  href="{% url 'acervo_pessoal:perfil' %}">
                    <img src="{% static 'images/profile.svg' %}">
                    <div class="login-texto">Meu perfil</div>
                </a>
            </li>
        </ul>
    </nav>
    <div class="nav-2-opcoes-escolha">
        <div class="cadastrar-livro-op"><a href="{% url 'acervo_pessoal:cadastrar_livro'%}">Cadastrar livro</a></div>
        <div class="registrar-livro-op"><a href="{% url 'acervo_pessoal:registrar_emprestimo'%}">Registrar empréstimo</a></div>
        <div class="cadastrar-contato-op"><a href="{% url 'acervo_pessoal:cadastrar_contato'%}">Cadastrar contato</a></div>
        <div class="registrar-devolucao-op"><a href="{% url 'acervo_pessoal:registrar_devolucao'%}">Registrar devolução</a></div>
        <div class="listar-itens-op"><a href="{% url 'acervo_pessoal:listar_itens'%}">Listar itens</a></div>
    </div>
    {% endblock %}
    {% block conteudo %}
    {% endblock %}
</body>
</html>

acervo_pessoal/templates/base_nao_logado.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    {% block head %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/base_nao_logado.css'%}">
    <title>{% block titulo %}Homepage{% endblock %}</title>
</head>
<body>
    {% block navbar %}
    <nav>
        <ul>
            <li  class="logo"><img src="{% static 'images/logo.svg' %}"></li>
            <li  class="logo-texto"><a href="{% url 'acervo_pessoal:home'%}">Acervo Pessoal Samara</a></li>
            <li  class="img-profile" style="float:right">
                <a  href="{% url 'acervo_pessoal:login'%}">
                    <img src="{% static 'images/profile.svg' %}">
                    <div class="login-texto">Login</div>
                </a>
            </li>
        </ul>
    </nav>
    {% endblock %}
    {% block conteudo %}
    {% endblock %}
</body>
</html>

acervo_pessoal/templates/cadastrar_contato.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/cadastrar_contato.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-cadastrar-contato">
        <div class="conteudo-colun1">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="" class="display-block item-cadastro-espaco label-cadastro-contato titulo-cadastro-contato">Cadastre um contato no seu acervo!</label>

                <label for="nome" class="display-block label-cadastro-contato">Digite o nome do contato</label>
                <input required type="text" class="display-block item-cadastro-espaco input-cadastro-contato"  name="nome" >
                
                <label for="email" class="display-block label-cadastro-contato">Digite o email</label>
                <input required type="email"  name="email" class="display-block item-cadastro-espaco input-cadastro-contato">
                
                <button class="botao-cadastro-contato">Cadastrar</button>

            </form>
        </div>
        <div class="conteudo-colun2">
            <p class="titulo-conteudo-colun2">Lista de contatos cadastrados no seu acervo:</p>
            {% for contato in contatos %}
            <ul class="ul-contatos-cadastrados-lista-geral">
                <li>{{contato.nome}} - {{contato.email}}</li>
            </ul>
            {%empty%}
                <p>Nenhum contato cadastrado no momento</p>
            {% endfor %}

        </div>
    </div>
    {% endblock %}

acervo_pessoal/templates/cadastrar_livro.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/cadastrar_livro.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-cadastrar-livro">
        <div class="conteudo-colun1">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="" class="display-block item-cadastro-espaco label-cadastro-livro titulo-cadastro-livro">Cadastre um livro no seu acervo!</label>

                <label for="" class="display-block label-cadastro-livro">Digite o nome do livro</label>
                <input type="text" class="display-block item-cadastro-espaco input-cadastro-livro"  name="nome_livro" >
                
                <label for="" class="display-block label-cadastro-livro">Digite o autor</label>
                <input type="text"  name="autor" class="display-block item-cadastro-espaco input-cadastro-livro">
                
                <label for="" class="display-block label-cadastro-livro">Digite o ano</label>
                <input type="text"  name="ano"  class="display-block item-cadastro-espaco input-cadastro-livro">

                <!--  foto do livro, solicitar -->
                <label for="" class="display-block label-cadastro-livro">Envie uma foto do livro</label>
                <input class="display-block item-cadastro-espaco" type="file" name="foto_livro" accept="image/*">

                <button class="botao-cadastro-livro">Cadastrar</button>

            </form>
        </div>
        <div class="conteudo-colun2">
            <p class="titulo-conteudo-colun2">Lista de livros cadastrados no seu acervo:</p>
            {% for livro in livros %}
            <ul class="ul-livros-cadastrados-lista-geral">
                <li>Livro: {{livro.nome}} -  Autor: {{livro.autor}} - Ano: {{livro.ano}}</li>
                <img src="{{ livro.foto.url }}" alt="" width="100" height="150">
            </ul>
            {%empty%}
                <p>Nenhum livro cadastrado no momento</p>
            {% endfor %}

        </div>
    </div>
    {% endblock %}

acervo_pessoal/templates/cadastro.html
{% extends 'base_nao_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/cadastro.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="formulario">
        <form action="" method="post"  class="formulario-cadastro">
            {% csrf_token %}
            <label class="display-block">Cadastro</label>

            <label class="display-block" for="fname">Nome</label>
            <input class="input-cadastro display-block" type="text" id="fname" name="fname" required>

            <label class="display-block" for="fusername">Username</label>
            <input class="input-cadastro display-block" type="text" id="fusername" name="fusername" required>

            <label for="lemail">Email</label>
            <input class="input-cadastro display-block" type="email" id="email" name="email" required>

            <label for="lname">Senha</label><br>
            <input class="input-cadastro display-block" type="password" id="password" name="password" required>

            <button type="submit" class="cadastro-enviar">Enviar</button>

            <p class="link-login display-block"><a href="{% url 'acervo_pessoal:login'%}">Já tem conta?<span class="amarelo-marcador"> fazer login</span></a></p>
        </form>
    </div>
{% endblock %}

acervo_pessoal/templates/home.html
{% extends 'base_nao_logado.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/home.css'%}">
{% endblock %}
{% block conteudo %}
<div class="conteudo-home">
    <div class="conteudo-home-coluna1">
        <div class="texto-coluna1">
            <h1><span class="amarelo-marcador">Organize</span> seus <span class="amarelo-marcador">livros</span> emprestados com <span class="amarelo-marcador">facilidade</span></h1>
            <button class="botao-cadastro" onclick="window.location.href='{% url 'acervo_pessoal:cadastro' %}'">Cadastre-se aqui!!</button>
        </div>
    </div>
    <div class="conteudo-home-coluna1">
        <img src="{% static 'images/img-home.svg'%}" alt="">
    </div>
</div>
{% endblock %}

acervo_pessoal/templates/listar_itens.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/listar_itens.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-itens">
        <div class="conteudo-colun1">
            <p class="titulo-conteudo-colun2">Livros disponíveis no seu acervo:</p>
            {% for livro_disponivel in livros_disponiveis %}
            <ul class="ul-itens-lista-geral"> 
                <li>
                    <ul class="ul-itens-lista-geral">
                        <li>Nome: {{livro_disponivel.nome}}</li>
                        <li>Autor: {{livro_disponivel.autor}}</li>
                        <img src="{{ livro_disponivel.foto.url }}" alt="" width="100" height="150">
                    </ul>
                </li>
            </ul>
            {%empty%}
                <p>Nenhum livro disponível</p>
            {% endfor %}
        </div>

        <div class="conteudo-colun2">
            <p class="titulo-conteudo-colun2">Livros emprestados no seu acervo:</p>
            {% for livro_emprestado in livros_emprestados %}
            <ul class="ul-itens-lista-geral"> 
                <li>
                    <ul class="ul-itens-lista-geral">
                        <li>Nome: {{livro_emprestado.nome}}</li>
                        <li>Livro: {{livro_emprestado.autor}}</li>
                        <img src="{{ livro_emprestado.foto.url }}" alt="" width="100" height="150">
                    </ul>
                </li>
            </ul>
            {%empty%}
                <p>Nenhum livro emprestado</p>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

acervo_pessoal/templates/livros_pesquisados.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/livros_pesquisados.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-itens">
        <div class="conteudo-colun1">
            <p class="titulo-conteudo-colun2">Livros:</p>
            {% for livro in livros %}
            <ul class="ul-itens-lista-geral"> 
                <li>
                    <ul class="ul-itens-lista-geral">
                        <li>Nome: {{livro.nome}}</li>
                        <li>Autor: {{livro.autor}}</li>
                        <img src="{{ livro.foto.url }}" alt="" width="100" height="150">
                    </ul>
                </li>
            </ul>
            {%empty%}
                <p>Nenhum livro disponível</p>
            {% endfor %}
        </div>
    </div>
    {% endblock %}

acervo_pessoal/templates/meu_perfil.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/meu_perfil.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-pagina-perfil">
        <div>
            <h1>Meu perfil</h1>
            <p>{{user.nome}}</p>
            <p>{{user.username}}</p>
            <p>{{user.email}}</p>
        </div>
        <div>
            <form action="{% url 'acervo_pessoal:logout' %}" method="post" class="botao-sair">
                {% csrf_token %}
                <button type="submit">
                    <img src="{% static 'images/logout-img.svg' %}" alt="">
                    <p>Logout</p>
            </form>
        </div>

    </div>
    {% endblock %}

acervo_pessoal/templates/pag_inicial_logado.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/pag_inicial_logado.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-pag-inicial-logado">
        <div class="conteudo-colun1">
            <h1>Bem vindo(a), {{ user.first_name }}! O que você quer fazer hoje? Escolha uma opção!</h1>

        </div>
        <div class="conteudo-colun2">
            <img src="{% static 'images/img-homepage.svg'%}" alt="">
        </div>
    </div>

    {% endblock %}

acervo_pessoal/templates/registrar_devolucao.html
{% extends 'base_logado.html' %}
{% load static %}
    {% block head %}
    <link rel="stylesheet" href="{% static 'css/registrar_devolucao.css'%}">
    {% endblock %}
    {% block conteudo %}
    <div class="conteudo-cadastrar-devolucao">
        <div class="conteudo-colun1">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="" class="display-block item-cadastro-espaco label-cadastro-devolucao titulo-cadastro-devolucao">Cadastre um devolucao no seu acervo!</label>

                <label for="nome" class="display-block label-cadastro-devolucao">Selecione um livro para registrar devolução</label>
                <select name="livro" id="" required class="display-block item-cadastro-espaco input-cadastro-devolucao">
                    <option value="" {% if not request.POST.livro %}selected{% endif %}>Selecione um livro</option>
                    {% for livro in livros_emprestados %}
                        <option value="{{ livro.id }}">{{ livro.nome}}</option>
                    {% endfor %}
                </select>
                
                <button class="botao-cadastro-devolucao">Registrar devolucao</button>

            </form>
        </div>
        <div class="conteudo-colun2">
            <p class="titulo-conteudo-colun2">Lista de empréstimos ATIVOS no seu acervo:</p>
            {% for emprestimo_ativo in emprestimos_ativos %}
            <ul class="ul-devolucaos-cadastrados-lista-geral"> 
                <li>
                    <ul class="ul-devolucaos-cadastrados-lista-geral">
                        <li>Nome: {{emprestimo_ativo.contato.nome}}</li>
                        <li>E-mail: {{emprestimo_ativo.contato.email}}</li>
                        <li>Livro: {{emprestimo_ativo.livro.nome}}</li>
                        <li>Status do empréstimo: {{ emprestimo_ativo.status_devolucao}} </li>
                        <li>Data empréstimo: {{emprestimo_ativo.data_devolucao}}</li>
                    </ul>
                </li>
            </ul>
            {%empty%}
                <p>Nenhuma devolução cadastrada no momento</p>
            {% endfor %}
        </div>
    </div>
    {% endblock %}